### ISSUE TITLE
Enable storage encryption for Wallets

### ISSUE THREAD

**Issue by marpme** [vergecurrency/MyVergies#5]
### Synopsis

We got a basic structure of the wallet-manager & wallet client now it's also important storing the credentials securely within the operating system and users storage devices.

### Technical Requirements

* would encrypt via the infallible themis framework which is covering JS (https://github.com/cossacklabs/themis)
* Store it encrypted on HDD/SSD's for to access 
(since they are sometimes willing to do backups of it)

**Comment by SwenVanZanten** [comment]
https://github.com/atom/node-keytar is used for wallet credentials storage.
This because this package uses native solutions on operating systems itself:
* macOS: Keychain
* Windows: Credential Vault
* Linux: Secret Service API/libsecret

The credentials are Base64 encoded simply because we will trust these OS tools.
Knowing all the used credentials in our OS's are already encrypted inside these tools it seems like overkill and unnecessary to double encrypt them. We can always look into it and migrate towards double encryption or file storage.

About system backups or credential backups:
Right now we don't support any system backup. Instead we'll add an export and import feature for credentials. And people need to save their paper key & passphrase's. Just like on iOS when you restore your phone from a backup.

**Comment by SwenVanZanten** [comment]
This has been implemented.
Will add an additional issue for creating the export function.
